
name: Build and Unit Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y clang-11 libc++-11-dev libc++abi-11-dev
      
    - name: SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.CXX_CORE_MP }} ${{ secrets.CXX_DEPENDS }}
        
    - name: Checkout cxx-core-mp
      uses: actions/checkout@v2
      with:
        repository: melton1968/cxx-core-mp
        path: cxx-core-mp
        
    - name: Checkout cxx-depends
      uses: actions/checkout@v2
      with:
        repository: melton1968/cxx-depends
        ref: migrate
        path: cxx-depends
        
    - name: Build dependencies
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir -p cxx-depends/build && pushd cxx-depends/build
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt ..
        make cxx_googletest cxx_core_pp install
        popd

    - name: Build and run the tests
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir -p cxx-core-mp/build && pushd cxx-core-mp/build
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt ..
        make
        make check
        make install
        popd
        
